Repository Sofie-Automation/sofie-core, pull requests merged in 2020-02, with the labels that each got.

#190 Fix: DeviceConfigManifest: creating default table rows
  meteor/client/ui/Settings/components/GenericDeviceSettingsComponent.tsx
Labels: bugfix

#174 Hidden Segments
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/RundownView/RundownOverview.tsx
  meteor/lib/collections/Segments.ts
Labels: Contribution from TV 2

#191 feat: log focus
  meteor/client/lib/clientAPI.ts
  meteor/client/ui/RundownView.tsx
  meteor/lib/api/userActions.ts
  meteor/server/api/__tests__/userActions.test.ts
  meteor/server/api/userActions.ts
Labels: enhancement

#192 feat: animated unfocused border in rundown
  meteor/client/styles/rundownView.scss
  meteor/client/ui/RundownView.tsx
  meteor/lib/Settings.ts
Labels: enhancement

#157 fix: improve UI performance
  meteor/client/main.js
  meteor/client/ui/RundownView/RundownNotifier.ts
  meteor/client/ui/RundownView/RundownOverview.tsx
  meteor/client/ui/RundownView/RundownSystemStatus.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
  meteor/client/ui/Settings/components/GenericDeviceSettingsComponent.tsx
  meteor/client/ui/Shelf/AdLibPanel.tsx
  meteor/lib/Rundown.ts
  meteor/lib/collections/Parts.ts
  meteor/lib/collections/Rundowns.ts
  meteor/package-lock.json
  meteor/package.json
  meteor/server/api/playout/lib.ts
  meteor/server/api/playout/playout.ts
Labels: bugfix, enhancement

#184 feat: Queued adlibs
  meteor/server/api/playout/adlib.ts
  meteor/server/api/playout/playout.ts
Labels: Contribution from TV 2

#199 feat: placeholder option for config manifests
  meteor/client/lib/EditAttribute.tsx
  meteor/client/ui/Settings/components/ConfigManifestEntryComponent.tsx
  meteor/lib/api/deviceConfig.ts
Labels: enhancement
