Repository Sofie-Automation/sofie-core, pull requests merged in 2020-04, with the labels that each got.

#218 fix: infinites spanning an autonext should take the end from the next part
  meteor/server/api/playout/timeline.ts
Labels: bugfix

#216 fix: part notes and invalidReason notes not showing
  meteor/client/ui/RundownView/RundownNotifier.ts
  meteor/client/ui/RundownView/RundownSystemStatus.tsx
  meteor/lib/api/notes.ts
  meteor/lib/api/rundown.ts
  meteor/lib/collections/Parts.ts
  meteor/lib/collections/RundownPlaylists.ts
  meteor/server/api/blueprints/__tests__/context.test.ts
  meteor/server/api/blueprints/context.ts
  meteor/server/api/ingest/rundownInput.ts
Labels: bugfix

#221 hotfix: prompter
  meteor/client/ui/Prompter/PrompterView.tsx
Labels: bugfix

#187 feat: option for sticky items to only make 'original' pieces sticky
  meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
  meteor/server/api/playout/adlib.ts
Labels: Contribution from TV 2

#183 feat: Add field for CasparCG mappings previewWhenNotOnAir property
  meteor/client/ui/Settings/StudioSettings.tsx
Labels: Contribution from TV 2

#181 feat: Timeline grab to scroll
  meteor/client/lib/PointerLockCursor.tsx
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimeline.scss
  meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
Labels: Contribution from TV 2

#182 MakeReady & StandDown
  meteor/server/api/playout/actions.ts
  meteor/server/api/playout/playout.ts
Labels: Contribution from TV 2

#180 feat: auto-expanding/collapsed segments
  meteor/.gitignore
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
Labels: Contribution from TV 2

#179 Snapshots handling
  meteor/lib/collections/Rundowns.ts
  meteor/server/api/ingest/ingestCache.ts
  meteor/server/api/playout/lib.ts
  meteor/server/api/snapshot.ts
Labels: Contribution from TV 2

#178 feat: Use source duration as fallback for VT
  meteor/client/ui/SegmentTimeline/SourceLayerItemContainer.tsx
  meteor/lib/mediaObjects.ts
Labels: Contribution from TV 2

#176 New feature: Set Next Segment
  meteor/client/lib/userAction.ts
  meteor/client/styles/rundownView.scss
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/SegmentTimeline/SegmentContextMenu.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
  meteor/lib/api/userActions.ts
  meteor/lib/collections/Rundowns.ts
  meteor/server/api/playout/actions.ts
  meteor/server/api/playout/lib.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/userActions.ts
Labels: Contribution from TV 2

#175 Feature: Zoom latch
  meteor/client/lib/rundown.ts
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/RundownView/RundownTiming.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
Labels: Contribution from TV 2

#172 Optimization when doing many Adlibs
  meteor/lib/collections/Pieces.ts
  meteor/server/api/playout/infinites.ts
  meteor/server/api/playout/lib.ts
  meteor/server/api/playout/timeline.ts
Labels: Contribution from TV 2

#171 Better Ingest-data management & unsync handling
  meteor/lib/lib.ts
  meteor/server/api/ingest/mosDevice/ingest.ts
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/rundown.ts
Labels: Contribution from TV 2

#167 Optimization: Lookahead max search distance
  meteor/client/ui/Settings/StudioSettings.tsx
  meteor/server/api/playout/adlib.ts
  meteor/server/api/playout/lookahead.ts
Labels: Contribution from TV 2

#194 fix: change timing of invalid & unplayed past parts, allow for outOfOrderTiming flag on rundown
  meteor/client/ui/RundownView/RundownOverview.tsx
  meteor/client/ui/RundownView/RundownTiming.tsx
  meteor/lib/collections/RundownPlaylists.ts
  meteor/package-lock.json
  meteor/package.json
  meteor/server/api/rundown.ts
Labels: bugfix, enhancement

#213 feat: playlist loop
  meteor/client/ui/RundownView/RundownTiming.tsx
  meteor/lib/collections/RundownPlaylists.ts
  meteor/package-lock.json
  meteor/package.json
  meteor/server/api/rundown.ts
Labels: enhancement
