Repository Sofie-Automation/sofie-core, pull requests merged in 2020-12, with the labels that each got.

#402 fix: return clientResponseError when normal operations instead of throwing in disableNextPiece
  meteor/client/ui/RundownView.tsx
  meteor/lib/api/__tests__/client.test.ts
  meteor/lib/api/client.ts
  meteor/lib/api/playout.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/userActions.ts
Labels: 🐛🔨 bugfix

#407 Feat: Local source layer type
  meteor/client/styles/_itemTypeColors.scss
  meteor/client/styles/defaultColors.scss
  meteor/client/ui/PieceIcons/Renderers/SplitInput.tsx
  meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
  packages/blueprints-integration/src/content.ts
Labels: Contribution from TV 2, ✨ enhancement

#401 feat: On air segment history
  meteor/client/lib/viewPort.ts
  meteor/lib/Settings.ts
Labels: Contribution from TV 2, ✨ enhancement

#399 Open shelf by default and shelf height settings
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/Settings/RundownLayoutEditor.tsx
  meteor/client/ui/Shelf/Shelf.tsx
  meteor/lib/collections/RundownLayouts.ts
  meteor/server/api/__tests__/rundownLayouts.test.ts
  meteor/server/api/rundownLayouts.ts
Labels: Contribution from TV 2, ✨ enhancement, 👍 Accepted

#398 fix: Unsynced Segment and updating Next
  meteor/server/api/ingest/genericDevice/actions.ts
  meteor/server/api/ingest/mosDevice/ingest.ts
  meteor/server/api/ingest/rundownInput.ts
Labels: Contribution from TV 2, 🐛🔨 bugfix, 👍 Accepted
