Repository Sofie-Automation/sofie-core, pull requests merged in 2020-08, with the labels that each got.

#285 fix: prevent a crash in getTimelineRundown by onTimelineGenerate
  meteor/server/api/playout/timeline.ts
Labels: Contribution from TV 2, bugfix

#295 fix: race condition in refresh part function
  meteor/server/DatabaseCache.ts
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/playout/lib.ts
Labels: Contribution from TV 2, bugfix

#267 feat: streamdeck buckets
  README.md
  meteor/client/styles/shelf/dashboard-streamdeck.scss
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/Shelf/BucketPanel.tsx
  meteor/client/ui/Shelf/DashboardPieceButton.tsx
  meteor/client/ui/Shelf/RundownViewBuckets.tsx
  meteor/client/ui/Shelf/Shelf.tsx
Labels: ✨ enhancement

#274 Adlib actions in dashboard
  meteor/client/ui/Shelf/AdLibListItem.tsx
  meteor/client/ui/Shelf/AdLibPanel.tsx
  meteor/client/ui/Shelf/AdLibRegionPanel.tsx
  meteor/client/ui/Shelf/DashboardPanel.tsx
  meteor/client/ui/Shelf/DashboardPieceButton.tsx
Labels: Contribution from TV 2, 👍 Accepted

#291 fix: measure HEADER_HEIGHT value for viewPort intersection and scrollTo
  meteor/client/lib/viewPort.ts
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
Labels: Contribution from TV 2, 👍 Accepted

#272 feat: notification & Notification Center tweaks
  meteor/.meteor/.gitignore
  meteor/client/lib/notificationIcons.tsx
  meteor/client/lib/notifications/NotificationCenterPanel.tsx
  meteor/client/lib/notifications/notifications.ts
  meteor/client/lib/reactiveData/reactiveData.ts
  meteor/client/lib/viewPort.ts
  meteor/client/styles/defaultColors.scss
  meteor/client/styles/notifications.scss
  meteor/client/styles/pieceStatusIcon.scss
  meteor/client/styles/rundownView.scss
  meteor/client/styles/statusbar.scss
  meteor/client/styles/supportPanel.scss
  meteor/client/ui/Header.tsx
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/RundownView/RundownFullscreenControls.tsx
  meteor/client/ui/RundownView/RundownNotifier.tsx
  meteor/client/ui/RundownView/RundownNotifier.tsx.rej
  meteor/client/ui/RundownView/RundownSystemStatus.tsx
  meteor/client/ui/SegmentTimeline/PieceStatusIcon.tsx
  meteor/client/ui/SegmentTimeline/Renderers/STKSourceRenderer.tsx
  meteor/client/ui/SegmentTimeline/Renderers/VTSourceRenderer.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimeline.scss
  meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
  meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
  meteor/client/ui/SegmentTimeline/SourceLayerItemContainer.tsx
  meteor/lib/__tests__/mediaObjects.test.ts
  meteor/lib/api/notes.ts
  meteor/lib/api/rundownNotifications.ts
  meteor/lib/collections/Parts.ts
  meteor/lib/collections/RundownPlaylists.ts
  meteor/lib/mediaObjects.ts
  meteor/lib/rundownNotifications.ts
Labels: ✨ enhancement

#305 Feat: Activation cache
  meteor/lib/collections/RundownPlaylists.ts
  meteor/lib/collections/Rundowns.ts
  meteor/lib/lib.ts
  meteor/lib/typings/meteor.d.ts
  meteor/package-lock.json
  meteor/package.json
  meteor/server/ActivationCache.ts
  meteor/server/DatabaseCache.ts
  meteor/server/DatabaseCaches.ts
  meteor/server/api/__tests__/expectedMediaItems.test.ts
  meteor/server/api/asRunLog.ts
  meteor/server/api/blueprints/__tests__/context-adlibActions.test.ts
  meteor/server/api/blueprints/__tests__/context.test.ts
  meteor/server/api/blueprints/__tests__/postProcess.test.ts
  meteor/server/api/blueprints/context/adlibActions.ts
  meteor/server/api/blueprints/context/context.ts
  meteor/server/api/ingest/__tests__/updateNext.test.ts
  meteor/server/api/ingest/actions.ts
  meteor/server/api/ingest/bucketAdlibs.ts
  meteor/server/api/ingest/mosDevice/__tests__/__snapshots__/mosIngest.test.ts.snap
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/manualPlayout.ts
  meteor/server/api/playout/__tests__/__snapshots__/api.test.ts.snap
  meteor/server/api/playout/__tests__/__snapshots__/playout.test.ts.snap
  meteor/server/api/playout/__tests__/__snapshots__/timeline.test.ts.snap
  meteor/server/api/playout/__tests__/actions.test.ts
  meteor/server/api/playout/actions.ts
  meteor/server/api/playout/adlib.ts
  meteor/server/api/playout/lib.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/playout/studio.ts
  meteor/server/api/playout/take.ts
  meteor/server/api/playout/timeline.ts
  meteor/server/api/testTools.ts
Labels: ✨ enhancement

#304 feat: elastic APM tracing
  meteor/.meteor/packages
  meteor/.meteor/versions
  meteor/__mocks__/_setupMocks.ts
  meteor/__mocks__/meteor-elastic-apm.ts
  meteor/client/ui/Settings.tsx
  meteor/client/ui/Settings/SystemManagement.tsx
  meteor/lib/__tests__/lib.test.ts
  meteor/lib/collections/CoreSystem.ts
  meteor/lib/lib.ts
  meteor/server/DatabaseCache.ts
  meteor/server/DatabaseCaches.ts
  meteor/server/api/asRunLog.ts
  meteor/server/api/blueprints/__tests__/context.test.ts
  meteor/server/api/blueprints/__tests__/postProcess.test.ts
  meteor/server/api/blueprints/context/context.ts
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/playout/actions.ts
  meteor/server/api/playout/adlib.ts
  meteor/server/api/playout/infinites.ts
  meteor/server/api/playout/lib.ts
  meteor/server/api/playout/lookahead.ts
  meteor/server/api/playout/pieces.ts
  meteor/server/api/playout/take.ts
  meteor/server/api/playout/timeline.ts
  meteor/server/api/snapshot.ts
  meteor/server/api/userActions.ts
  meteor/server/coreSystem.ts
  meteor/server/publications/system.ts
  meteor/server/security/collections.ts
  meteor/server/typings/meteor-kschingiz-elastic-apm.d.ts
Labels: ✨ enhancement

#303 Feat: Blueprint config restructure and cache
  meteor/__mocks__/helpers/database.ts
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
  meteor/client/ui/Settings/ConfigManifestSettings.tsx
  meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
  meteor/client/ui/Settings/StudioSettings.tsx
  meteor/client/ui/Shelf/Inspector/ItemRenderers/ActionItemRenderer.tsx
  meteor/lib/collections/ShowStyleBases.ts
  meteor/lib/collections/ShowStyleVariants.ts
  meteor/lib/collections/Studios.ts
  meteor/package-lock.json
  meteor/package.json
  meteor/server/__tests__/_testEnvironment.test.ts
  meteor/server/api/blueprints/__tests__/config.test.ts
  meteor/server/api/blueprints/__tests__/context.test.ts
  meteor/server/api/blueprints/__tests__/migrationContext.test.ts
  meteor/server/api/blueprints/cache.ts
  meteor/server/api/blueprints/config.ts
  meteor/server/api/blueprints/context/context.ts
  meteor/server/api/blueprints/migrationContext.ts
  meteor/server/api/ingest/__tests__/updateNext.test.ts
  meteor/server/api/playout/actions.ts
  meteor/server/api/rundown.ts
  meteor/server/api/showStyles.ts
  meteor/server/api/studios.ts
  meteor/server/coreSystem.ts
  meteor/server/migration/0_19_0.ts
  meteor/server/migration/0_1_0.ts
  meteor/server/migration/1_0_0.ts
  meteor/server/migration/1_11_0.ts
  meteor/server/migration/X_X_X.ts
  meteor/server/migration/__tests__/migrations.test.ts
  meteor/server/migration/deprecatedDataTypes/1_10_0.ts
Labels: Contribution from TV 2, ✨ enhancement

#298 Feat: nrcs name rundown
  meteor/__mocks__/helpers/database.ts
  meteor/client/lib/language.ts
  meteor/client/ui/ClipTrimPanel/ClipTrimDialog.tsx
  meteor/client/ui/RundownList.tsx
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/RundownView/RundownNotifier.tsx
  meteor/client/ui/RundownView/RundownSystemStatus.tsx
  meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
  meteor/i18n/template.pot
  meteor/lib/collections/PeripheralDevices.ts
  meteor/lib/collections/Rundowns.ts
  meteor/public/locales/nb/translations.json
  meteor/public/locales/nn/translations.json
  meteor/server/__tests__/cronjobs.test.ts
  meteor/server/api/__tests__/expectedMediaItems.test.ts
  meteor/server/api/__tests__/externalMessageQueue.test.ts
  meteor/server/api/__tests__/peripheralDevice.test.ts
  meteor/server/api/blueprints/__tests__/cache.test.ts
  meteor/server/api/blueprints/__tests__/postProcess.test.ts
  meteor/server/api/ingest/__tests__/updateNext.test.ts
  meteor/server/api/ingest/mosDevice/__tests__/__snapshots__/mosIngest.test.ts.snap
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/playout/__tests__/__snapshots__/playout.test.ts.snap
Labels: Contribution from TV 2, 👍 Accepted

#294 chore: remove commented out console.log and other inactive code
  meteor/__mocks__/helpers/database.ts
  meteor/__mocks__/mongo.ts
  meteor/client/lib/ReactMeteorData/ReactMeteorData.tsx
  meteor/client/lib/SettingsNavigation.tsx
  meteor/client/lib/VirtualElement.tsx
  meteor/client/lib/clientAPI.ts
  meteor/client/lib/mousetrapHelper.ts
  meteor/client/lib/reactiveData/reactiveDataHelper.ts
  meteor/client/lib/viewPort.ts
  meteor/client/ui/AfterBroadcastForm.tsx
  meteor/client/ui/Prompter/controller/keyboard-device.ts
  meteor/client/ui/Prompter/controller/mouse-ish-device.ts
  meteor/client/ui/RundownList.tsx
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/RundownView/RundownNotifier.tsx
  meteor/client/ui/RundownView/RundownTiming.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelineZoomControls.tsx
  meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
  meteor/client/ui/SegmentTimeline/SourceLayerItemContainer.tsx
  meteor/client/ui/SegmentTimeline/TimelineGrid.tsx
  meteor/client/ui/Settings/BlueprintSettings.tsx
  meteor/client/ui/Settings/DeviceSettings.tsx
  meteor/client/ui/Settings/Migration.tsx
  meteor/client/ui/Settings/RundownLayoutEditor.tsx
  meteor/client/ui/Settings/StudioSettings.tsx
  meteor/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx
  meteor/client/ui/Shelf/AdLibPanel.tsx
  meteor/client/ui/Shelf/BucketPanel.tsx
  meteor/client/ui/Shelf/DashboardPanel.tsx
  meteor/client/ui/Shelf/ExternalFramePanel.tsx
  meteor/client/ui/Shelf/GlobalAdLibPanel.tsx
  meteor/client/ui/Shelf/Shelf.tsx
  meteor/client/ui/Status/MediaManager.tsx
  meteor/client/ui/Status/SystemStatus.tsx
  meteor/client/ui/TestTools/RecordingsList.tsx
  meteor/client/ui/TestTools/Timeline.tsx
  meteor/scripts/generate-version-file.js
  meteor/server/api/ExternalMessageQueue.ts
  meteor/server/api/__tests__/peripheralDevice.test.ts
  meteor/server/api/blueprints/migrationContext.ts
  meteor/server/api/client.ts
  meteor/server/api/ingest/mosDevice/__tests__/mosIngest.test.ts
  meteor/server/api/integration/rabbitMQ.ts
  meteor/server/api/integration/soap.ts
  meteor/server/api/playout/timeline.ts
  meteor/server/api/rest/rest.ts
  meteor/server/logging.ts
  meteor/server/performanceMonitor.ts
  meteor/server/security/lib/lib.ts
Labels: 🧹chore
