Repository Sofie-Automation/sofie-core, pull requests merged in 2020-09, with the labels that each got.

#275 Mappings & Timeline routing
  meteor/__mocks__/helpers/database.ts
  meteor/__mocks__/helpers/snapshot.ts
  meteor/client/lib/EditAttribute.tsx
  meteor/client/lib/userAction.ts
  meteor/client/styles/settings.scss
  meteor/client/styles/statusbar.scss
  meteor/client/styles/supportPanel.scss
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/RundownView/RundownRightHandControls.tsx
  meteor/client/ui/Settings/RundownLayoutEditor.tsx
  meteor/client/ui/Settings/SnapshotsView.tsx
  meteor/client/ui/Settings/StudioSettings.tsx
  meteor/client/ui/Status/ExternalMessages.tsx
  meteor/client/ui/Status/SystemStatus.tsx
  meteor/client/ui/TestTools/Timeline.tsx
  meteor/lib/__tests__/lib.test.ts
  meteor/lib/api/playout.ts
  meteor/lib/api/pubsub.ts
  meteor/lib/api/userActions.ts
  meteor/lib/collections/Studios.ts
  meteor/lib/collections/Timeline.ts
  meteor/lib/lib.ts
  meteor/package-lock.json
  meteor/package.json
  meteor/server/DatabaseCache.ts
  meteor/server/DatabaseCaches.ts
  meteor/server/__tests__/_testEnvironment.test.ts
  meteor/server/api/__tests__/peripheralDevice.test.ts
  meteor/server/api/ingest/__tests__/updateNext.test.ts
  meteor/server/api/manualPlayout.ts
  meteor/server/api/peripheralDevice.ts
  meteor/server/api/playout/__tests__/__snapshots__/playout.test.ts.snap
  meteor/server/api/playout/__tests__/__snapshots__/timeline.test.ts.snap
  meteor/server/api/playout/__tests__/playout.test.ts
  meteor/server/api/playout/api.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/playout/timeline.ts
  meteor/server/api/snapshot.ts
  meteor/server/api/studios.ts
  meteor/server/api/system.ts
  meteor/server/api/userActions.ts
  meteor/server/lib/customPublication.ts
  meteor/server/lib/optimizedObserver.ts
  meteor/server/migration/0_1_0.ts
  meteor/server/migration/0_25_0.ts
  meteor/server/migration/X_X_X.ts
  meteor/server/migration/__tests__/migrations.test.ts
  meteor/server/migration/deprecatedDataTypes/1_11_0.ts
  meteor/server/publications/_publications.ts
  meteor/server/publications/studio.ts
  meteor/server/publications/timeline.ts
  meteor/server/security/studio.ts
Labels: ✨ enhancement

#328 chore: update framework to Meteor 1.11
  Dockerfile
  Dockerfile.circle
  meteor/.meteor/.finished-upgraders
  meteor/.meteor/packages
  meteor/.meteor/release
  meteor/.meteor/versions
  meteor/package-lock.json
Labels: dependency update

#314 fix: Don't register sticky piece hotkeys twice in dashboard
  meteor/client/ui/Shelf/DashboardPanel.tsx
Labels: Contribution from TV 2, 🐛🔨 bugfix

#329 Fix/readonly caches
  meteor/server/DatabaseCaches.ts
  meteor/server/api/asRunLog.ts
  meteor/server/api/blueprints/context/context.ts
  meteor/server/api/peripheralDevice.ts
Labels: 🐛🔨 bugfix

#327 Gui Optimizations
  meteor/client/lib/rundown.ts
  meteor/client/lib/viewPort.ts
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/RundownView/RundownSystemStatus.tsx
  meteor/client/ui/RundownView/RundownTiming.tsx
  meteor/client/ui/SegmentTimeline/SegmentContextMenu.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelinePart.tsx
Labels: Contribution from TV 2

#316 feat: Add method to remove MediaObjects with specific collectionId
  meteor/lib/api/peripheralDevice.ts
  meteor/server/api/integration/media-scanner.ts
  meteor/server/api/peripheralDevice.ts
Labels: Contribution from TV 2

#309 Feat/tally tags
  meteor/client/styles/shelf/adLibRegionPanel.scss
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/Shelf/AdLibPanel.tsx
  meteor/client/ui/Shelf/AdLibRegionPanel.tsx
  meteor/client/ui/Shelf/BucketPanel.tsx
  meteor/client/ui/Shelf/DashboardPanel.tsx
  meteor/client/ui/Shelf/TimelineDashboardPanel.tsx
  meteor/package-lock.json
  meteor/server/api/blueprints/__tests__/context-adlibActions.test.ts
  meteor/server/api/blueprints/context/adlibActions.ts
Labels: Contribution from TV 2, 👍 Accepted

#319 Add names to anonymous rundown playlist sync functions
  meteor/package-lock.json
  meteor/package.json
  meteor/server/__tests__/codeControl.test.ts
  meteor/server/api/expectedMediaItems.ts
  meteor/server/api/ingest/actions.ts
  meteor/server/api/ingest/mosDevice/ingest.ts
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/peripheralDevice.ts
  meteor/server/api/playout/adlib.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/playout/take.ts
  meteor/server/codeControl.ts
  meteor/server/coreSystem.ts
  meteor/server/mockData/rundownData.ts
Labels: 🌟 Code improvement

#326 Contribute: Various fixes from TV 2
  meteor/client/styles/rundownView.scss
  meteor/client/ui/App.tsx
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimeline.scss
  meteor/client/ui/Shelf/DashboardPanel.tsx
  meteor/client/ui/Shelf/DashboardPieceButton.tsx
  meteor/lib/rundown/infinites.ts
  meteor/server/api/ingest/expectedPlayoutItems.ts
  meteor/server/api/playout/infinites.ts
Labels: Contribution from TV 2
