Repository Sofie-Automation/sofie-core, pull requests merged in 2020-11, with the labels that each got.

#358 Feat: dataSegmentGet peripheral device method
  meteor/lib/api/peripheralDevice.ts
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/peripheralDevice.ts
Labels: Contribution from TV 2, 👍 Accepted

#335 Feat/playlist reordering ui
  meteor/client/lib/userAction.ts
  meteor/client/styles/fonts/roboto.scss
  meteor/client/styles/fonts/sass/_Black.scss
  meteor/client/styles/fonts/sass/_BlackItalic.scss
  meteor/client/styles/fonts/sass/_Bold.scss
  meteor/client/styles/fonts/sass/_BoldItalic.scss
  meteor/client/styles/fonts/sass/_Italic.scss
  meteor/client/styles/fonts/sass/_Light.scss
  meteor/client/styles/fonts/sass/_LightItalic.scss
  meteor/client/styles/fonts/sass/_Medium.scss
  meteor/client/styles/fonts/sass/_MediumItalic.scss
  meteor/client/styles/fonts/sass/_Regular.scss
  meteor/client/styles/fonts/sass/_Thin.scss
  meteor/client/styles/fonts/sass/_ThinItalic.scss
  meteor/client/styles/fonts/sass/_mixins.scss
  meteor/client/styles/fonts/sass/_variables.scss
  meteor/client/styles/fonts/sass/roboto.scss
  meteor/client/styles/main.scss
  meteor/client/styles/rundownList.scss
  meteor/client/ui/RundownList.tsx
  meteor/client/ui/RundownList/ActiveProgressBar.tsx
  meteor/client/ui/RundownList/DragAndDropTypes.ts
  meteor/client/ui/RundownList/GettingStarted.tsx
  meteor/client/ui/RundownList/JonasFormattedTime.tsx
  meteor/client/ui/RundownList/PlaylistRankMethodToggle.tsx
  meteor/client/ui/RundownList/RegisterHelp.tsx
  meteor/client/ui/RundownList/RundownDropZone.tsx
  meteor/client/ui/RundownList/RundownListFooter.tsx
  meteor/client/ui/RundownList/RundownListItem.tsx
  meteor/client/ui/RundownList/RundownListItemProblems.tsx
  meteor/client/ui/RundownList/RundownListItemView.tsx
  meteor/client/ui/RundownList/RundownPlaylistDragLayer.tsx
  meteor/client/ui/RundownList/RundownPlaylistUi.tsx
  meteor/client/ui/RundownList/__tests__/DragAndDropTypes.test.ts
  meteor/client/ui/RundownList/icons.tsx
  meteor/client/ui/RundownList/old/RundownListItem.tsx
  meteor/client/ui/RundownList/util.ts
  meteor/client/ui/RundownView.tsx
  meteor/lib/Settings.ts
  meteor/lib/api/playout.ts
  meteor/lib/api/rundown.ts
  meteor/lib/api/userActions.ts
  meteor/lib/collections/RundownPlaylists.ts
  meteor/lib/collections/Rundowns.ts
  meteor/lib/lib.ts
  meteor/server/api/__tests__/rundown.test.ts
  meteor/server/api/ingest/mosDevice/__tests__/__snapshots__/mosIngest.test.ts.snap
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/playout/__tests__/playout.test.ts
  meteor/server/api/playout/api.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/rundown.ts
  meteor/server/api/rundownPlaylist.ts
  meteor/server/api/userActions.ts
  meteor/server/security/rundownPlaylist.ts
Labels: ✨ enhancement

#369 fix: Remove deleted segments from ingestDataCache
  meteor/server/api/ingest/rundownInput.ts
Labels: Contribution from TV 2, 🐛🔨 bugfix
