Repository Sofie-Automation/sofie-core, pull requests merged in 2021-12, with the labels that each got.

#631 fix: Hash triggers for core migrations
  meteor/server/migration/1_37_0.ts
  meteor/server/migration/X_X_X.ts
Labels: 🐛🔨 bugfix, Contribution from TV 2, 👍 Accepted

#628 chore: fix pre-commit script to work on Linux and macOS
  .husky/pre-commit
Labels: Contribution from TV 2, 🧹chore, 👍 Accepted

#626 fix: make pieceIds generate without relying on the segmentId, so that they are stable when parts are moved between segments
  meteor/lib/hash.ts
  meteor/lib/lib.ts
  meteor/server/api/blueprints/__tests__/context-adlibActions.test.ts
  meteor/server/api/blueprints/__tests__/postProcess.test.ts
  meteor/server/api/blueprints/context/adlibActions.ts
  meteor/server/api/blueprints/context/syncIngestUpdateToPartInstance.ts
  meteor/server/api/blueprints/postProcess.ts
  meteor/server/api/ingest/generation.ts
  meteor/server/api/ingest/mosDevice/diff.ts
  meteor/server/cache/CacheCollection.ts
Labels: 🌟 Code improvement

#630 chore: add default VS Code settings
  .vscode/settings.json.default
  README.md
Labels: 🧹chore

#632 feat: make PeripheralDeviceApi.executeFunction and friends return a p…
  meteor/client/lib/dev.ts
  meteor/client/ui/Settings/DevicePackageManagerSettings.tsx
  meteor/lib/api/peripheralDevice.ts
  meteor/lib/lib.ts
  meteor/server/__tests__/cronjobs.test.ts
  meteor/server/api/__tests__/peripheralDevice.test.ts
  meteor/server/api/blueprints/api.ts
  meteor/server/api/client.ts
  meteor/server/api/evaluations.ts
  meteor/server/api/ingest/__tests__/ingest.test.ts
  meteor/server/api/ingest/actions.ts
  meteor/server/api/ingest/genericDevice/actions.ts
  meteor/server/api/ingest/mosDevice/__tests__/actions.test.ts
  meteor/server/api/ingest/mosDevice/actions.ts
  meteor/server/api/integration/slack.ts
  meteor/server/api/mediaManager.ts
  meteor/server/api/packageManager.ts
  meteor/server/api/peripheralDevice.ts
  meteor/server/api/playout/__tests__/playout.test.ts
  meteor/server/api/playout/actions.ts
  meteor/server/api/playout/timeline.ts
  meteor/server/api/rundown.ts
  meteor/server/api/snapshot.ts
  meteor/server/api/system.ts
  meteor/server/api/userActions.ts
  meteor/server/cronjobs.ts
  meteor/server/lib.ts
Labels: 🌟 Code improvement
