Repository Sofie-Automation/sofie-core, pull requests merged in 2021-03, with the labels that each got.

#410 feat: Add CasparCG cron job system setting
  meteor/client/ui/Settings/SystemManagement.tsx
  meteor/lib/collections/CoreSystem.ts
  meteor/server/__tests__/cronjobs.test.ts
  meteor/server/coreSystem.ts
  meteor/server/cronjobs.ts
  meteor/server/migration/X_X_X.ts
  meteor/server/publications/system.ts
  meteor/server/security/collections.ts
Labels: Contribution from TV 2, ✨ enhancement, 👍 Accepted

#435 feat: Add PieceCountdownPanel
  meteor/client/styles/shelf/pieceCountdownPanel.scss
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/Settings/RundownLayoutEditor.tsx
  meteor/client/ui/Shelf/PieceCountdownPanel.tsx
  meteor/client/ui/Shelf/ShelfDashboardLayout.tsx
  meteor/lib/api/rundownLayouts.ts
  meteor/lib/collections/RundownLayouts.ts
Labels: Contribution from TV 2, ✨ enhancement, 👍 Accepted

#437 feat: segmentRanksUpdate peripheral device method
  meteor/lib/api/peripheralDevice.ts
  meteor/server/api/ingest/__tests__/ingest.test.ts
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/peripheralDevice.ts
  packages/server-core-integration/src/lib/corePeripherals.ts
Labels: Contribution from TV 2, ✨ enhancement, 👍 Accepted

#438 fix: Upload snapshots where part externalId is missing
  meteor/server/api/snapshot.ts
Labels: Contribution from TV 2, 🐛🔨 bugfix, 👍 Accepted

#443 fix: blueprintConfig dropped when restoring a snapshot
  meteor/server/migration/1_12_0.ts
Labels: Contribution from TV 2, 🐛🔨 bugfix, 👍 Accepted

#447 fix: Restore shelf layout selection to lobby
  meteor/client/styles/rundownList.scss
  meteor/client/styles/splitDropdown.scss
  meteor/client/ui/RundownList.tsx
  meteor/client/ui/RundownList/DragAndDropTypes.ts
  meteor/client/ui/RundownList/RundownListItem.tsx
  meteor/client/ui/RundownList/RundownListItemView.tsx
  meteor/client/ui/RundownList/RundownPlaylistDragLayer.tsx
  meteor/client/ui/RundownList/RundownPlaylistUi.tsx
  meteor/client/ui/RundownList/RundownShelfLayoutSelection.tsx
Labels: Contribution from TV 2, 🐛🔨 bugfix, 👍 Accepted

#448 fix: Don't use NTP servers in tests
  meteor/server/api/systemTime/systemTime.ts
  meteor/server/coreSystem.ts
  meteor/server/systemStatus/__tests__/systemStatus.test.ts
Labels: Contribution from TV 2, 🐛🔨 bugfix, 👍 Accepted

#436 Show restart button only for device notifications >= WARNING_MAJOR
  meteor/client/ui/RundownView/RundownNotifier.tsx
  packages/server-core-integration/src/lib/corePeripherals.ts
Labels: Contribution from TV 2, ✨ enhancement, 👍 Accepted

#461 Fix: Take after execute cache usage in takeNextPartInnerSync
  meteor/server/api/playout/take.ts
Labels: Contribution from TV 2, 🐛🔨 bugfix, 👍 Accepted

#452 feat: staggered segment updates
  meteor/__mocks__/tracker.ts
  meteor/client/lib/VirtualElement.tsx
  meteor/client/lib/__tests__/rundown.test.ts
  meteor/client/lib/reactiveData/__tests__/reactiveDataHelper.test.ts
  meteor/client/lib/reactiveData/reactiveDataHelper.ts
  meteor/client/lib/rundown.ts
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
  meteor/lib/Rundown.ts
  meteor/package-lock.json
Labels: Contribution from TV 2, ✨ enhancement
