Repository Sofie-Automation/sofie-core, pull requests merged in 2021-11, with the labels that each got.

#622 Fix: protect against blueprint throws
  meteor/lib/lib.ts
  meteor/server/api/blueprints/config.ts
  meteor/server/api/blueprints/events.ts
  meteor/server/api/ingest/bucketAdlibs.ts
  meteor/server/api/ingest/generation.ts
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/ingest/syncChangesToPartInstance.ts
  meteor/server/api/playout/actions.ts
  meteor/server/api/playout/adlib.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/playout/take.ts
  meteor/server/api/playout/timeline.ts
  meteor/server/api/rundown.ts
  meteor/server/api/rundownPlaylist.ts
Labels: 🌟 Code improvement

#581 fix: rewinding and scrolling next part
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
Labels: 🐛🔨 bugfix, Contribution from TV 2

#620 fix: Queued segment looping until cleared manually
  meteor/server/api/playout/lib.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/playout/take.ts
  meteor/server/api/userActions.ts
Labels: 🐛🔨 bugfix, Contribution from TV 2, 👍 Accepted
