Repository Sofie-Automation/sofie-core, pull requests merged in 2021-09, with the labels that each got.

#560 fix: Assign ranks according to playlist order by rundownExternalId
  meteor/server/api/ingest/commit.ts
  meteor/server/api/rundownPlaylist.ts
Labels: 🐛🔨 bugfix, Contribution from TV 2, 👍 Accepted

#555 fix: AdLibs from other Rundowns in a Playlist can't be started, even uf they use the same ShowStyleVariant
  meteor/server/api/playout/adlib.ts
Labels: 🐛🔨 bugfix, Contribution from TV 2, 👍 Accepted

#557 chore: Remove Segment Resync
  meteor/client/lib/userAction.ts
  meteor/client/ui/RundownView.tsx
  meteor/client/ui/SegmentTimeline/SegmentContextMenu.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
  meteor/lib/api/peripheralDevice.ts
  meteor/lib/api/rundown.ts
  meteor/lib/api/userActions.ts
  meteor/server/api/__tests__/rundownPlaylist.test.ts
  meteor/server/api/__tests__/userActions/general.test.ts
  meteor/server/api/ingest/actions.ts
  meteor/server/api/ingest/genericDevice/actions.ts
  meteor/server/api/rundown.ts
  meteor/server/api/userActions.ts
Labels: Contribution from TV 2, 👍 Accepted

#562 fix: ENPS hardcoded in rundown order toggle label
  meteor/client/ui/RundownList/PlaylistRankMethodToggle.tsx
  meteor/client/ui/RundownList/RundownPlaylistUi.tsx
  meteor/i18n/nb.po
  meteor/i18n/nn.po
  meteor/i18n/template.pot
  meteor/public/locales/nb/translations.json
  meteor/public/locales/nn/translations.json
Labels: 🐛🔨 bugfix, Contribution from TV 2, 👍 Accepted

#561 fix: moveNext when using segmentDelta
  meteor/server/api/playout/playout.ts
Labels: 🐛🔨 bugfix, Contribution from TV 2, 👍 Accepted

#564 Fix: media status polling
  meteor/client/ui/RundownView/RundownNotifier.tsx
  meteor/lib/api/rundownNotifications.ts
  meteor/lib/lib.ts
  meteor/server/api/rundownNotifications.ts
Labels: 🐛🔨 bugfix

#584 chore: fix vscode debugging configuration
  .vscode/launch.json
Labels: Contribution from TV 2, 👍 Accepted
