Repository Sofie-Automation/sofie-core, pull requests merged in 2022-05, with the labels that each got.

#720 fix(Prompter): If collection changes are slow, Prompter may receive incomplete updates, and render some Script missing
  meteor/client/ui/Prompter/PrompterView.tsx
  meteor/lib/api/prompter.ts
Labels: 🐛🔨 bugfix

#719 fix: OAuth code returned via redirect_uri
  meteor/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx
  meteor/server/api/peripheralDevice.ts
Labels: ✨ enhancement, Contribution from SuperFly.tv

#655 fix: dashboard panel scale affecting position
  meteor/client/styles/shelf/dashboard.scss
  meteor/client/ui/Shelf/DashboardPanel.tsx
  meteor/client/ui/Shelf/NextInfoPanel.tsx
  meteor/client/ui/Shelf/PieceCountdownPanel.tsx
Labels: 🐛🔨 bugfix, Contribution from TV 2

#708 feat: use Sorensen prevent default down option and configurable poison key
  meteor/client/lib/triggers/TriggersHandler.tsx
  meteor/lib/Settings.ts
  meteor/package.json
  meteor/yarn.lock
Labels: Contribution from TV 2
