Repository Sofie-Automation/sofie-core, pull requests merged in 2022-01, with the labels that each got.

#619 feat: Per piece prerollDuration
  meteor/__mocks__/defaultCollectionObjects.ts
  meteor/__mocks__/helpers/database.ts
  meteor/client/lib/__tests__/__snapshots__/rundown.test.ts.snap
  meteor/client/lib/rundown.ts
  meteor/client/styles/testtools.scss
  meteor/client/ui/ClockView/PresenterScreen.tsx
  meteor/client/ui/RundownView/RundownOverview.tsx
  meteor/client/ui/RundownView/RundownTiming/SegmentDuration.tsx
  meteor/client/ui/SegmentTimeline/Parts/SegmentTimelinePart.tsx
  meteor/client/ui/SegmentTimeline/Renderers/MicSourceRenderer.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
  meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
  meteor/client/ui/Shelf/DashboardPieceButton.tsx
  meteor/client/ui/Shelf/Renderers/L3rdListItemRenderer.tsx
  meteor/client/ui/TestTools/Timeline.tsx
  meteor/lib/__tests__/mediaObjects.test.ts
  meteor/lib/collections/PartInstances.ts
  meteor/lib/collections/Parts.ts
  meteor/lib/collections/Pieces.ts
  meteor/lib/rundown/__tests__/infinites.test.ts
  meteor/lib/rundown/__tests__/rundownTiming.test.ts
  meteor/lib/rundown/__tests__/timings.test.ts
  meteor/lib/rundown/infinites.ts
  meteor/lib/rundown/rundownTiming.ts
  meteor/lib/rundown/timings.ts
  meteor/package-lock.json
  meteor/server/api/__tests__/peripheralDevice.test.ts
  meteor/server/api/__tests__/rundown-updatePartInstanceRanks.test.ts
  meteor/server/api/blueprints/__tests__/context-adlibActions.test.ts
  meteor/server/api/blueprints/__tests__/postProcess.test.ts
  meteor/server/api/blueprints/context/adlibActions.ts
  meteor/server/api/blueprints/context/lib.ts
  meteor/server/api/blueprints/postProcess.ts
  meteor/server/api/ingest/__tests__/updateNext.test.ts
  meteor/server/api/ingest/generation.ts
  meteor/server/api/ingest/syncChangesToPartInstance.ts
  meteor/server/api/peripheralDevice.ts
  meteor/server/api/playout/DOCS.md
  meteor/server/api/playout/__tests__/__snapshots__/timeline.test.ts.snap
  meteor/server/api/playout/__tests__/helpers/rundowns.ts
  meteor/server/api/playout/__tests__/timeline.test.ts
  meteor/server/api/playout/adlib.ts
  meteor/server/api/playout/lib.ts
  meteor/server/api/playout/lookahead/__tests__/findObjects.test.ts
  meteor/server/api/playout/lookahead/__tests__/lookahead.test.ts
  meteor/server/api/playout/lookahead/__tests__/util.test.ts
  meteor/server/api/playout/lookahead/findObjects.ts
  meteor/server/api/playout/pieces.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/playout/take.ts
  meteor/server/api/playout/timeline.ts
  meteor/server/migration/X_X_X.ts
  packages/blueprints-integration/src/context.ts
  packages/blueprints-integration/src/rundown.ts
  packages/documentation/docs/for-developers/_part-timings-demo.jsx
  packages/documentation/docs/for-developers/part-and-piece-timings.mdx
Labels: ✨ enhancement

#642 Fix: expetedPackages from snapshot
  meteor/server/api/snapshot.ts
Labels: 🐛🔨 bugfix

#627 fix: reset instances from previous activation or not present in cache
  meteor/server/api/playout/__tests__/playout.test.ts
  meteor/server/api/playout/cache.ts
  meteor/server/api/playout/lib.ts
Labels: 🐛🔨 bugfix, Contribution from TV 2

#650 docs: fix CasparCG Media Scanner links
  packages/documentation/docs/getting-started/installation/installing-connections-and-additional-hardware/casparcg-server-installation.md
Labels: Contribution from SuperFly.tv, 📖 Documentation

#644 docs: rename spreadsheet-blueprints to demo-blueprints
  packages/documentation/docs/getting-started/installation/installing-a-gateway/rundown-or-newsroom-system-connection/installing-sofie-with-google-spreadsheet-support.md
  packages/documentation/docs/getting-started/installation/installing-blueprints.md
  packages/documentation/docs/main/features-and-configuration/concepts-and-architecture.md
  packages/documentation/docs/main/resources.md
  packages/documentation/versioned_docs/version-1.32.0/getting-started/installation/installing-blueprints.md
  packages/documentation/versioned_docs/version-1.32.0/main/features-and-configuration/concepts-and-architecture.md
  packages/documentation/versioned_docs/version-1.32.0/main/resources.md
Labels: Contribution from SuperFly.tv, 📖 Documentation

#652 docs: add basic demo docs for Package Manager
  packages/documentation/docs/getting-started/installation/installing-package-manager.md
  packages/documentation/static/img/docs/Package_Manager_status_example.jpg
Labels: Contribution from SuperFly.tv, 📖 Documentation

#638 Contribute: bugfixes release38
  meteor/__mocks__/helpers/database.ts
  meteor/client/lib/reactiveData/reactiveDataHelper.ts
  meteor/client/ui/RundownView/RundownNotifier.tsx
  meteor/client/ui/SegmentContainer/withResolvedSegment.ts
  meteor/lib/collections/Segments.ts
  meteor/lib/rundownNotifications.ts
  meteor/server/api/blueprints/context/context.ts
  meteor/server/api/blueprints/context/syncIngestUpdateToPartInstance.ts
  meteor/server/api/ingest/__tests__/ingest.test.ts
  meteor/server/api/ingest/commit.ts
  meteor/server/api/ingest/generation.ts
  meteor/server/api/ingest/lib.ts
  meteor/server/api/ingest/mosDevice/diff.ts
  meteor/server/api/ingest/shouldRemoveOrphanedPartInstance.ts
  meteor/server/api/playout/actions.ts
  meteor/server/api/playout/lib.ts
  meteor/server/api/playout/pieces.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/userActions.ts
  meteor/server/codeControl.ts
  packages/blueprints-integration/src/api.ts
Labels: 🐛🔨 bugfix, Contribution from TV 2

#659 fix: PGW: old device names in log
  packages/playout-gateway/src/tsrHandler.ts
Labels: 🐛🔨 bugfix

#661 docs: update example docker-compose.yaml
  packages/documentation/docs/getting-started/installation/installing-sofie-server-core.md
  packages/documentation/static/attachments/docs/getting-started/installation/docker-compose.yaml
Labels: 📖 Documentation

#665 fix: show adLibs from different show-styles as disabled
  meteor/client/styles/contextMenu.scss
  meteor/client/styles/shelf/adLibPanel.scss
  meteor/client/ui/Shelf/AdLibListItem.tsx
  meteor/client/ui/Shelf/AdLibPanel.tsx
  meteor/client/ui/Shelf/DashboardPanel.tsx
  meteor/client/ui/Shelf/ShelfContextMenu.tsx
  meteor/lib/collections/RundownPlaylists.ts
Labels: 🐛🔨 bugfix

#666 fix: ask confirmation before restarting playout gateway
  meteor/client/ui/RundownView.tsx
Labels: 🐛🔨 bugfix
