Repository Sofie-Automation/sofie-core, pull requests merged in 2023-01, with the labels that each got.

#829 fix: Queued parts at the end of a playlist
  meteor/client/ui/RundownView/RundownTiming/RundownTimingProvider.tsx
Labels: 🐛🔨 bugfix, Contribution from others

#826 fix: OAuth controls
  meteor/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx
  meteor/server/api/peripheralDevice.ts
Labels: Contribution from others

#810 TV2 Sync: Merge current develop into R49
  meteor/.eslintrc.js
  meteor/__mocks__/helpers/database.ts
  meteor/client/lib/Components/TextInput.tsx
  meteor/client/styles/settings.scss
  meteor/client/ui/App.tsx
  meteor/client/ui/Settings/ShowStyle/DragDropTypesShowStyle.ts
  meteor/client/ui/Settings/ShowStyle/VariantListItem.tsx
  meteor/client/ui/Settings/ShowStyle/VariantSettings.tsx
  meteor/client/ui/Settings/ShowStyleBaseSettings.tsx
  meteor/client/ui/Settings/components/ConfigManifestEntryComponent.tsx
  meteor/client/ui/globals/keyboardGlobals.d.ts
  meteor/lib/api/showStyles.ts
  meteor/lib/collections/ShowStyleVariants.ts
  meteor/server/api/blueprints/__tests__/migrationContext.test.ts
  meteor/server/api/blueprints/migrationContext.ts
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/showStyles.ts
  meteor/server/migration/0_1_0.ts
  meteor/server/migration/X_X_X.ts
  meteor/server/migration/__tests__/migrations.test.ts
  meteor/server/publications/showStyle.ts
  packages/corelib/src/dataModel/ShowStyleVariant.ts
  packages/job-worker/src/__mocks__/presetCollections.ts
  packages/job-worker/src/ingest/expectedMediaItems.ts
  packages/job-worker/src/ingest/expectedPackages.ts
  packages/mos-gateway/package.json
  packages/playout-gateway/src/configManifest.ts
  packages/playout-gateway/src/tsrHandler.ts
Labels: Contribution from TV 2
