Repository Sofie-Automation/sofie-core, pull requests merged in 2023-06, with the labels that each got.

#951 feat: improve the styling of Test Tools
  meteor/client/styles/testtools.scss
  meteor/client/ui/TestTools/Timeline.tsx
  meteor/client/ui/TestTools/TimelineDatastore.tsx
Labels: ✨ enhancement, Contribution from others

#928 Allow blueprint debugging
  .vscode/launch.json
  README.md
  meteor/__mocks__/_vm2.ts
  meteor/server/api/blueprints/cache.ts
  meteor/server/worker/worker.ts
  packages/corelib/src/worker/shared.ts
  packages/job-worker/src/blueprints/cache.ts
  packages/job-worker/src/ipc.ts
  packages/job-worker/src/main.ts
  packages/job-worker/src/workers/events/parent.ts
  packages/job-worker/src/workers/ingest/parent.ts
  packages/job-worker/src/workers/parent-base.ts
  packages/job-worker/src/workers/studio/parent.ts
  packages/job-worker/src/workers/worker-set.ts
Labels: ✨ enhancement, Contribution from SuperFly.tv

#960 fix: hide countdown and icicles on looping media
  meteor/client/ui/SegmentList/LinePartTimeline.tsx
  meteor/client/ui/SegmentTimeline/Renderers/CustomLayerItemRenderer.tsx
  meteor/client/ui/SegmentTimeline/Renderers/VTSourceRenderer.tsx
Labels: 🐛🔨 bugfix, Contribution from others

#954 fix: Improve API responses
  meteor/server/api/rest/v1/index.ts
  packages/corelib/src/error.ts
  packages/live-status-gateway/src/coreHandler.ts
  packages/openapi/api/definitions/showstyles.yaml
  packages/openapi/api/definitions/studios.yaml
  packages/openapi/src/__tests__/devices.spec.ts
  packages/openapi/src/__tests__/playlists.spec.ts
  packages/openapi/src/__tests__/sofie.spec.ts
  packages/openapi/src/__tests__/studios.spec.ts
Labels: 🐛🔨 bugfix, Contributions from EVS

#976 fix: custom publications overly reactive
  meteor/server/publications/packageManager/expectedPackages/contentCache.ts
  meteor/server/publications/packageManager/expectedPackages/contentObserver.ts
  meteor/server/publications/packageManager/expectedPackages/publication.ts
  meteor/server/publications/pieceContentStatusUI/bucket/bucketContentCache.ts
  meteor/server/publications/pieceContentStatusUI/bucket/bucketContentObserver.ts
  meteor/server/publications/pieceContentStatusUI/bucket/publication.ts
  meteor/server/publications/pieceContentStatusUI/rundown/publication.ts
  meteor/server/publications/pieceContentStatusUI/rundown/reactiveContentCache.ts
  meteor/server/publications/pieceContentStatusUI/rundown/rundownContentObserver.ts
  meteor/server/publications/segmentPartNotesUI/publication.ts
  meteor/server/publications/segmentPartNotesUI/reactiveContentCache.ts
  meteor/server/publications/segmentPartNotesUI/rundownContentObserver.ts
Labels: 🐛🔨 bugfix, Contribution from others
