Repository Sofie-Automation/sofie-core, pull requests merged in 2023-05, with the labels that each got.

#917 feat: Expose MOS Gateway ports in settings
  packages/mos-gateway/src/$schemas/devices.json
  packages/mos-gateway/src/$schemas/options.json
  packages/mos-gateway/src/generated/devices.ts
  packages/mos-gateway/src/generated/options.ts
  packages/mos-gateway/src/mosHandler.ts
Labels: ✨ enhancement, Contribution from others

#903 fix: reduce the amount of visual jitter on a playing timeline, particularly on scaled DPIs
  meteor/client/lib/rundownTiming.ts
  meteor/client/styles/rundownView.scss
  meteor/client/ui/SegmentTimeline/Parts/SegmentTimelinePart.tsx
  meteor/client/ui/SegmentTimeline/SegmentTimeline.scss
  meteor/client/ui/SegmentTimeline/SegmentTimeline.tsx
  meteor/client/ui/SegmentTimeline/SmallParts/SegmentTimelinePartHoverPreview.tsx
Labels: 🐛🔨 bugfix, Contribution from SuperFly.tv

#934 feat: allow nested config tables
  meteor/client/lib/forms/SchemaFormTable/ArrayTable.tsx
  meteor/client/lib/forms/SchemaFormTable/ObjectTable.scss
  meteor/client/lib/forms/SchemaFormTable/ObjectTable.tsx
  meteor/client/lib/forms/SchemaFormTable/TableEditRow.tsx
Labels: ✨ enhancement, Contribution from SuperFly.tv

#933 feat: improve the visual layout of all settings pages
  meteor/client/lib/Components/LabelAndOverrides.tsx
  meteor/client/lib/forms/SchemaFormTable/TableEditRow.tsx
  meteor/client/lib/forms/SchemaFormWithOverrides.tsx
  meteor/client/ui/Settings/BlueprintConfigSchema/CategoryEntry.tsx
  meteor/client/ui/Settings/BlueprintSettings.tsx
  meteor/client/ui/Settings/DeviceSettings.tsx
  meteor/client/ui/Settings/Forms.scss
  meteor/client/ui/Settings/RundownLayoutEditor.tsx
  meteor/client/ui/Settings/ShowStyle/BlueprintConfiguration/SelectBlueprint.tsx
  meteor/client/ui/Settings/ShowStyle/BlueprintConfiguration/SelectConfigPreset.tsx
  meteor/client/ui/Settings/ShowStyle/Generic.tsx
  meteor/client/ui/Settings/ShowStyle/HotkeyLegend.tsx
  meteor/client/ui/Settings/ShowStyle/OutputLayer.tsx
  meteor/client/ui/Settings/ShowStyle/SourceLayer.tsx
  meteor/client/ui/Settings/ShowStyle/VariantListItem.tsx
  meteor/client/ui/Settings/SnapshotsView.tsx
  meteor/client/ui/Settings/Studio/BlueprintConfiguration/SelectBlueprint.tsx
  meteor/client/ui/Settings/Studio/BlueprintConfiguration/SelectConfigPreset.tsx
  meteor/client/ui/Settings/Studio/Devices/GenericSubDevices.tsx
  meteor/client/ui/Settings/Studio/Generic.tsx
  meteor/client/ui/Settings/Studio/Mappings.tsx
  meteor/client/ui/Settings/Studio/PackageManager.tsx
  meteor/client/ui/Settings/Studio/Routings.tsx
  meteor/client/ui/Settings/SystemManagement.tsx
  meteor/client/ui/Settings/components/ConfigManifestEntryComponent.tsx
  meteor/client/ui/Settings/components/FilterEditor.tsx
  meteor/client/ui/Settings/components/GenericDeviceSettingsComponent.tsx
  meteor/client/ui/Settings/components/rundownLayouts/RundownHeaderLayoutSettings.tsx
  meteor/client/ui/Settings/components/rundownLayouts/RundownViewLayoutSettings.tsx
  meteor/client/ui/Settings/components/rundownLayouts/ShelfLayoutSettings.tsx
  meteor/client/ui/Settings/components/triggeredActions/TriggeredActionEntry.tsx
  meteor/client/ui/Status/StatusCodePill.tsx
Labels: ✨ enhancement, Contribution from SuperFly.tv
