Repository Sofie-Automation/sofie-core, pull requests merged in 2024-10, with the labels that each got.

#1268 chore: disable nrk specific workflows
  .github/workflows/prune-container-images.yml
  .github/workflows/prune-tags.yml
  .github/workflows/trivy.yml
Labels: Contribution from BBC

#1270 fix: clear pieces with fixed duration
  packages/job-worker/src/playout/adlibUtils.ts
Labels: Contribution from BBC

#1276 fix: on change infinites incorrect collision ends
  packages/job-worker/src/playout/timeline/rundown.ts
Labels: 🐛🔨 bugfix, Contribution from BBC

#1272 feat: routeset controlled ab player availability
  meteor/server/migration/X_X_X.ts
  packages/blueprints-integration/src/abPlayback.ts
  packages/corelib/src/dataModel/Studio.ts
  packages/corelib/src/overrideOpHelper.ts
  packages/job-worker/src/playout/abPlayback/__tests__/abPlayback.spec.ts
  packages/job-worker/src/playout/abPlayback/__tests__/abPlaybackResolver.spec.ts
  packages/job-worker/src/playout/abPlayback/__tests__/routeSetDisabling.spec.ts
  packages/job-worker/src/playout/abPlayback/abPlaybackResolver.ts
  packages/job-worker/src/playout/abPlayback/abPlaybackSessions.ts
  packages/job-worker/src/playout/abPlayback/applyAssignments.ts
  packages/job-worker/src/playout/abPlayback/index.ts
  packages/job-worker/src/playout/abPlayback/routeSetDisabling.ts
  packages/job-worker/src/playout/upgrade.ts
  packages/job-worker/src/studio/model/StudioBaselineHelper.ts
  packages/shared-lib/src/core/model/StudioRouteSet.ts
  packages/webui/src/client/ui/Settings/Studio/Routings/RouteSetAbPlayers.tsx
  packages/webui/src/client/ui/Settings/Studio/Routings/RouteSets.tsx
Labels: Contribution from BBC

#1285 fix: regenerate timeline after routeset
  packages/job-worker/src/blueprints/context/adlibActions.ts
  packages/job-worker/src/playout/adlibAction.ts
  packages/job-worker/src/playout/debug.ts
  packages/job-worker/src/playout/lib.ts
  packages/job-worker/src/playout/model/PlayoutModel.ts
  packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts
  packages/job-worker/src/studio/model/StudioBaselineHelper.ts
  packages/job-worker/src/studio/model/StudioPlayoutModel.ts
  packages/job-worker/src/studio/model/StudioPlayoutModelImpl.ts
  packages/job-worker/src/studio/routeSet.ts
Labels: Contribution from BBC

#1278 feat: rework user permissions in the ui to use a react context
  packages/webui/src/client/lib/KeyboardFocusIndicator.tsx
  packages/webui/src/client/lib/localStorage.ts
  packages/webui/src/client/lib/logStatus.ts
  packages/webui/src/client/ui/App.tsx
  packages/webui/src/client/ui/RundownList.tsx
  packages/webui/src/client/ui/RundownList/RundownListItem.tsx
  packages/webui/src/client/ui/RundownList/RundownListItemView.tsx
  packages/webui/src/client/ui/RundownList/RundownPlaylistUi.tsx
  packages/webui/src/client/ui/RundownList/util.ts
  packages/webui/src/client/ui/RundownView.tsx
  packages/webui/src/client/ui/RundownView/RundownNotifier.tsx
  packages/webui/src/client/ui/Settings/components/GenericDeviceSettingsComponent.tsx
  packages/webui/src/client/ui/Status.tsx
  packages/webui/src/client/ui/Status/ExternalMessages.tsx
  packages/webui/src/client/ui/Status/MediaManager.tsx
  packages/webui/src/client/ui/Status/StatusCodePill.tsx
  packages/webui/src/client/ui/Status/SystemStatus.tsx
  packages/webui/src/client/ui/Status/SystemStatus/CoreItem.tsx
  packages/webui/src/client/ui/Status/SystemStatus/DeviceItem.tsx
  packages/webui/src/client/ui/Status/SystemStatus/SystemStatus.tsx
  packages/webui/src/client/ui/UserPermissions.tsx
Labels: Contribution from BBC

#1263 feat: package manager config defined in blueprints
  meteor/__mocks__/defaultCollectionObjects.ts
  meteor/server/api/rest/v1/typeConversion.ts
  meteor/server/api/studio/api.ts
  meteor/server/migration/0_1_0.ts
  meteor/server/migration/X_X_X.ts
  meteor/server/migration/__tests__/migrations.test.ts
  meteor/server/publications/packageManager/expectedPackages/generate.ts
  meteor/server/publications/packageManager/expectedPackages/publication.ts
  meteor/server/publications/packageManager/packageContainers.ts
  meteor/server/publications/pieceContentStatusUI/__tests__/checkPieceContentStatus.test.ts
  meteor/server/publications/pieceContentStatusUI/checkPieceContentStatus.ts
  meteor/server/publications/pieceContentStatusUI/common.ts
  packages/blueprints-integration/src/api/studio.ts
  packages/corelib/src/dataModel/Studio.ts
  packages/job-worker/src/__mocks__/defaultCollectionObjects.ts
  packages/job-worker/src/playout/upgrade.ts
  packages/shared-lib/src/core/model/PackageContainer.ts
  packages/webui/src/__mocks__/defaultCollectionObjects.ts
  packages/webui/src/client/lib/Components/LabelAndOverrides.tsx
  packages/webui/src/client/ui/Settings/Studio/PackageManager.tsx
  packages/webui/src/client/ui/Settings/Studio/PackageManager/AccessorTable.tsx
  packages/webui/src/client/ui/Settings/Studio/PackageManager/AccessorTableRow.tsx
  packages/webui/src/client/ui/Settings/Studio/PackageManager/PackageContainerPickers.tsx
  packages/webui/src/client/ui/Settings/Studio/PackageManager/PackageContainers.tsx
  packages/webui/src/client/ui/Settings/Studio/PackageManager/index.tsx
Labels: Contribution from BBC

#1292 fix: remove unused meteor ui packages
  meteor/.meteor/packages
  meteor/.meteor/versions
  meteor/server/main.ts
Labels: Contribution, Contribution from BBC

#1296 Fix: prompter skips script pieces
  packages/webui/src/client/ui/Prompter/prompter.ts
Labels: 🐛🔨 bugfix, Contribution from BBC

#1283 fix: QuickLoop timers are inconsistent
  packages/job-worker/src/playout/model/PlayoutModel.ts
  packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts
  packages/job-worker/src/playout/model/services/QuickLoopService.ts
  packages/job-worker/src/playout/quickLoopMarkers.ts
  packages/webui/src/client/lib/rundownTiming.ts
Labels: Contribution from BBC

#1298 Add playlist timings to LSG
  packages/live-status-gateway/api/schemas/activePlaylist.yaml
  packages/live-status-gateway/src/topics/__tests__/activePlaylist.spec.ts
  packages/live-status-gateway/src/topics/activePlaylistTopic.ts
Labels: ✨ enhancement, Contribution from BBC

#1299 fix: Segment component crash (sofie-3542)
  meteor/client/ui/SegmentStoryboard/SegmentStoryboard.tsx
  meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/Renderers/ThumbnailRendererFactory.tsx
  meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnail.tsx
  meteor/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnailInner.tsx
Labels: 🐛🔨 bugfix

#1301 Feature: list routesets in adlib actions
  packages/blueprints-integration/src/context/adlibActionContext.ts
  packages/blueprints-integration/src/context/routeSetContext.ts
  packages/job-worker/src/blueprints/context/adlibActions.ts
  packages/webui/src/client/ui/Status/SystemStatus/SystemStatus.tsx
Labels: ✨ enhancement, Contribution from BBC

#1277 feat: add segment budget timing #1188
  packages/blueprints-integration/src/documents/part.ts
  packages/blueprints-integration/src/documents/segment.ts
  packages/corelib/src/dataModel/RundownPlaylist.ts
  packages/job-worker/src/blueprints/context/lib.ts
  packages/job-worker/src/playout/model/PlayoutModel.ts
  packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts
  packages/job-worker/src/playout/timings/partPlayback.ts
  packages/live-status-gateway/api/schemas/activePlaylist.yaml
  packages/live-status-gateway/api/schemas/segments.yaml
  packages/live-status-gateway/src/collections/segmentHandler.ts
  packages/live-status-gateway/src/liveStatusServer.ts
  packages/live-status-gateway/src/topics/__tests__/activePlaylist.spec.ts
  packages/live-status-gateway/src/topics/__tests__/segmentsTopic.spec.ts
  packages/live-status-gateway/src/topics/activePlaylistTopic.ts
  packages/live-status-gateway/src/topics/helpers/segmentTiming.ts
  packages/live-status-gateway/src/topics/segmentsTopic.ts
  packages/webui/src/client/lib/__tests__/rundownTiming.test.ts
  packages/webui/src/client/lib/rundownTiming.ts
  packages/webui/src/client/ui/ClockView/CameraScreen/Part.tsx
  packages/webui/src/client/ui/ClockView/PresenterScreen.tsx
  packages/webui/src/client/ui/RundownView.tsx
  packages/webui/src/client/ui/RundownView/RundownTiming/CurrentPartOrSegmentRemaining.tsx
  packages/webui/src/client/ui/RundownView/RundownTiming/SegmentDuration.tsx
  packages/webui/src/client/ui/SegmentAdlibTesting/SegmentAdlibTesting.tsx
  packages/webui/src/client/ui/SegmentAdlibTesting/SegmentAdlibTestingContainer.tsx
  packages/webui/src/client/ui/SegmentContainer/withResolvedSegment.ts
  packages/webui/src/client/ui/SegmentList/LinePart.tsx
  packages/webui/src/client/ui/SegmentList/OnAirLine.tsx
  packages/webui/src/client/ui/SegmentList/SegmentListHeader.tsx
  packages/webui/src/client/ui/SegmentStoryboard/SegmentStoryboard.tsx
  packages/webui/src/client/ui/SegmentStoryboard/SegmentStoryboardContainer.tsx
  packages/webui/src/client/ui/SegmentStoryboard/StoryboardPart.tsx
  packages/webui/src/client/ui/SegmentTimeline/SegmentTimeline.tsx
  packages/webui/src/client/ui/SegmentTimeline/SegmentTimelineContainer.tsx
  packages/webui/src/client/ui/Shelf/PartTimingPanel.tsx
  packages/webui/src/client/ui/Shelf/SegmentTimingPanel.tsx
Labels: Contribution from BBC

#1291 fix: `handleSwitchRouteSet` builds timeline with stale studio routeSets
  packages/corelib/src/overrideOpHelper.ts
  packages/job-worker/src/__mocks__/context.ts
  packages/job-worker/src/jobs/index.ts
  packages/job-worker/src/playout/abPlayback/__tests__/routeSetDisabling.spec.ts
  packages/job-worker/src/playout/abPlayback/routeSetDisabling.ts
  packages/job-worker/src/playout/model/implementation/PlayoutModelImpl.ts
  packages/job-worker/src/studio/model/StudioBaselineHelper.ts
  packages/job-worker/src/studio/model/StudioPlayoutModelImpl.ts
  packages/job-worker/src/workers/caches.ts
  packages/job-worker/src/workers/context/JobContextImpl.ts
  packages/job-worker/src/workers/context/Locks.ts
  packages/job-worker/src/workers/context/StudioCacheContextImpl.ts
  packages/job-worker/src/workers/context/StudioRouteSetUpdater.ts
  packages/job-worker/src/workers/context/__tests__/StudioRouteSetUpdater.spec.ts
  packages/job-worker/src/workers/context/util.ts
  packages/job-worker/src/workers/events/child.ts
  packages/job-worker/src/workers/ingest/child.ts
  packages/job-worker/src/workers/studio/child.ts
  packages/webui/src/client/ui/Settings/Studio/Routings/RouteSetAbPlayers.tsx
Labels: 🐛🔨 bugfix, Contribution from BBC

#1295 feat: add `notes` to `RundownPlaylist` and pipe notes from blueprints from `getRundownPlaylistInfo` and `getShowStyleId`
  meteor/server/publications/lib/quickLoop.ts
  packages/corelib/src/dataModel/Notes.ts
  packages/corelib/src/dataModel/RundownPlaylist.ts
  packages/corelib/src/lib.ts
  packages/job-worker/src/blueprints/context/StudioUserContext.ts
  packages/job-worker/src/ingest/__tests__/selectShowStyleVariant.test.ts
  packages/job-worker/src/ingest/generationRundown.ts
  packages/job-worker/src/ingest/mosDevice/__tests__/__snapshots__/mosIngest.test.ts.snap
  packages/job-worker/src/rundownPlaylists.ts
  packages/meteor-lib/src/lib.ts
  packages/meteor-lib/src/triggers/actionFilterChainCompilers.ts
  packages/webui/src/client/lib/tempLib.ts
  packages/webui/src/client/ui/RundownView/RundownNotifier.tsx
Labels: Contribution from BBC
