Repository Sofie-Automation/sofie-core, pull requests merged in 2025-03, with the labels that each got.

#1389 fix(Core): omit privateData in bucket adlib pieces and actions publications
  meteor/server/publications/buckets.ts
Labels: Contribution, Contribution from TV 2 Norge

#1367 refactor(LSG): get rid of async in handlers; extract shared logic to base classes
  meteor/server/api/rest/v0/__tests__/rest.test.ts
  meteor/server/migration/1_52_0.ts
  packages/corelib/src/worker/studio.ts
  packages/live-status-gateway/src/collectionBase.ts
  packages/live-status-gateway/src/collections/adLibActionsHandler.ts
  packages/live-status-gateway/src/collections/adLibsHandler.ts
  packages/live-status-gateway/src/collections/globalAdLibActionsHandler.ts
  packages/live-status-gateway/src/collections/globalAdLibsHandler.ts
  packages/live-status-gateway/src/collections/partHandler.ts
  packages/live-status-gateway/src/collections/partInstancesHandler.ts
  packages/live-status-gateway/src/collections/partsHandler.ts
  packages/live-status-gateway/src/collections/pieceInstancesHandler.ts
  packages/live-status-gateway/src/collections/playlistHandler.ts
  packages/live-status-gateway/src/collections/rundownContentHandlerBase.ts
  packages/live-status-gateway/src/collections/rundownHandler.ts
  packages/live-status-gateway/src/collections/rundownsHandler.ts
  packages/live-status-gateway/src/collections/segmentHandler.ts
  packages/live-status-gateway/src/collections/segmentsHandler.ts
  packages/live-status-gateway/src/collections/showStyleBaseHandler.ts
  packages/live-status-gateway/src/collections/studioHandler.ts
  packages/live-status-gateway/src/helpers/equality.ts
  packages/live-status-gateway/src/liveStatusServer.ts
  packages/live-status-gateway/src/publicationCollection.ts
  packages/live-status-gateway/src/topics/__tests__/activePieces.spec.ts
  packages/live-status-gateway/src/topics/__tests__/activePlaylist.spec.ts
  packages/live-status-gateway/src/topics/__tests__/adLibs.spec.ts
  packages/live-status-gateway/src/topics/__tests__/segmentsTopic.spec.ts
  packages/live-status-gateway/src/topics/__tests__/utils.ts
  packages/live-status-gateway/src/topics/activePiecesTopic.ts
  packages/live-status-gateway/src/topics/activePlaylistTopic.ts
  packages/live-status-gateway/src/topics/adLibsTopic.ts
  packages/live-status-gateway/src/topics/helpers/segmentTiming.ts
  packages/live-status-gateway/src/topics/root.ts
  packages/live-status-gateway/src/topics/segmentsTopic.ts
  packages/live-status-gateway/src/topics/studioTopic.ts
  packages/live-status-gateway/src/wsHandler.ts
  packages/shared-lib/src/lib/types.ts
  packages/webui/src/client/lib/clientUserAction.ts
  packages/webui/src/client/ui/RundownView.tsx
  packages/webui/src/client/ui/Settings/Studio/Generic.tsx
  packages/webui/src/client/ui/Settings/components/triggeredActions/actionEditors/actionSelector/ActionSelector.tsx
Labels: Contribution, Contribution from TV 2 Norge

#1374 feat: implement tally for device trigger previews
  meteor/server/api/deviceTriggers/PieceInstancesObserver.ts
  meteor/server/api/deviceTriggers/StudioDeviceTriggerManager.ts
  meteor/server/api/deviceTriggers/StudioObserver.ts
  meteor/server/api/deviceTriggers/TagsService.ts
  meteor/server/api/deviceTriggers/__tests__/TagsService.test.ts
  meteor/server/api/deviceTriggers/observer.ts
  meteor/server/api/deviceTriggers/reactiveContentCacheForPieceInstances.ts
  packages/corelib/src/lib.ts
  packages/meteor-lib/src/triggers/actionFilterChainCompilers.ts
  packages/shared-lib/src/input-gateway/deviceTriggerPreviews.ts
Labels: Contribution, Contribution from TV 2 Norge

#1393 feat(Blueprint API): Expose Segments in blueprint contexts
  packages/blueprints-integration/src/context/onSetAsNextContext.ts
  packages/blueprints-integration/src/context/partsAndPieceActionContext.ts
  packages/job-worker/src/blueprints/__tests__/context-OnSetAsNextContext.test.ts
  packages/job-worker/src/blueprints/__tests__/context-OnTakeContext.test.ts
  packages/job-worker/src/blueprints/__tests__/context-adlibActions.test.ts
  packages/job-worker/src/blueprints/context/OnSetAsNextContext.ts
  packages/job-worker/src/blueprints/context/OnTakeContext.ts
  packages/job-worker/src/blueprints/context/adlibActions.ts
  packages/job-worker/src/blueprints/context/services/PartAndPieceInstanceActionService.ts
Labels: Contribution, Contribution from BBC

#1381 fix(Core): simplify meteor collection auth checks
  .github/actions/setup-meteor/action.yaml
  .node-version
  meteor/.meteor/packages
  meteor/.meteor/release
  meteor/.meteor/versions
  meteor/Dockerfile
  meteor/package.json
  meteor/server/collections/collection.ts
  package.json
  packages/blueprints-integration/package.json
  packages/corelib/package.json
  packages/documentation/package.json
  packages/job-worker/package.json
  packages/live-status-gateway/package.json
  packages/meteor-lib/package.json
  packages/mos-gateway/package.json
  packages/playout-gateway/package.json
  packages/server-core-integration/package.json
  packages/shared-lib/package.json
  packages/webui/package.json
  packages/webui/vite.config.mts
Labels: Contribution, Contribution from BBC

#1397 fix: stringify error in executeAction
  packages/playout-gateway/src/coreHandler.ts
Labels: 🐛🔨 bugfix, Contribution, Contribution from TV 2 Norge

#1396 fix: prevent queued Part from hijacking infinite Pieces from the following Part(s)
  packages/job-worker/src/blueprints/context/services/PartAndPieceInstanceActionService.ts
  packages/job-worker/src/blueprints/context/services/__tests__/PartAndPieceInstanceActionService.test.ts
  packages/job-worker/src/ingest/__tests__/ingest.test.ts
  packages/job-worker/src/playout/adlibUtils.ts
Labels: Contribution, Contribution from TV 2 Norge

#1398 feat: mini shelfview
  packages/webui/src/client/ui/SegmentList/SegmentListContainer.tsx
  packages/webui/src/client/ui/SegmentStoryboard/SegmentStoryboardContainer.tsx
Labels: Contribution, Contribution from BBC

#1385 feat(Test Tools): show AB-Session in Timeline
  packages/webui/src/client/ui/TestTools/Timeline.tsx
Labels: Contribution, Contribution from BBC

#1412 fix(Segment Storyboard): sorted storyboard sourcelayers (SOFIE-3433)
  packages/webui/src/client/ui/SegmentStoryboard/SegmentStoryboard.tsx
  packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartSecondaryPieces/StoryboardPartSecondaryPieces.tsx
  packages/webui/src/client/ui/SegmentTimeline/SegmentTimeline.tsx
Labels: 🐛🔨 bugfix

#1387 Gateway types available for blueprints
  packages/blueprints-integration/src/api/studio.ts
  packages/live-status-gateway/src/coreHandler.ts
  packages/mos-gateway/src/mosHandler.ts
  packages/playout-gateway/src/coreHandler.ts
  packages/playout-gateway/src/tsrHandler.ts
  packages/scripts/schema-types.mjs
  packages/shared-lib/src/generated/LiveStatusGatewayOptionsTypes.ts
  packages/shared-lib/src/generated/MosGatewayDevicesTypes.ts
  packages/shared-lib/src/generated/MosGatewayOptionsTypes.ts
  packages/shared-lib/src/generated/PlayoutGatewayConfigTypes.ts
Labels: Contribution, Contribution from BBC

#1410 fix: reimplement `removePartInstance` flow for `syncChangesToPartInstances`
  packages/blueprints-integration/src/context/syncIngestChangesContext.ts
  packages/job-worker/src/blueprints/context/SyncIngestUpdateToPartInstanceContext.ts
  packages/job-worker/src/ingest/__tests__/syncChangesToPartInstance.test.ts
  packages/job-worker/src/ingest/syncChangesToPartInstance.ts
Labels: 🐛🔨 bugfix, Contribution, Contribution from BBC

#1400 fix(dependencies): remove velocity React (SOFIE-3716)
  packages/webui/package.json
  packages/webui/public/origo-ui/dist/origo.css
  packages/webui/src/client/lib/ModalDialog.tsx
  packages/webui/src/client/lib/notifications/NotificationCenterPanel.tsx
  packages/webui/src/client/lib/utilComponents.tsx
  packages/webui/src/client/styles/notifications.scss
  packages/webui/src/client/styles/supportAndSwitchboardPanel.scss
  packages/webui/src/client/ui/App.tsx
  packages/webui/src/client/ui/ClockView/OverlayScreenSaver.tsx
  packages/webui/src/client/ui/FloatingInspectors/VTFloatingInspector.tsx
  packages/webui/src/client/ui/Header.tsx
  packages/webui/src/client/ui/Prompter/PrompterView.tsx
  packages/webui/src/client/ui/RundownList.tsx
  packages/webui/src/client/ui/RundownView.tsx
  packages/webui/src/client/ui/RundownView/MediaStatusPopUp/index.tsx
  packages/webui/src/client/ui/RundownView/PopUpPanel.tsx
  packages/webui/src/client/ui/RundownView/RundownNotifier.tsx
  packages/webui/src/client/ui/RundownView/RundownRightHandButton.tsx
  packages/webui/src/client/ui/RundownView/RundownRightHandControls.tsx
  packages/webui/src/client/ui/RundownView/SwitchboardPopUp.tsx
  packages/webui/src/client/ui/SegmentAdlibTesting/SegmentAdlibTesting.tsx
  packages/webui/src/client/ui/SegmentStoryboard/SegmentStoryboard.tsx
  packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartSecondaryPieces/StoryboardPartSecondaryPieces.scss
  packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartSecondaryPieces/StoryboardSecondaryPiece.tsx
  packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartSecondaryPieces/StoryboardSourceLayer.tsx
  packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartSecondaryPieces/StoryboardSourceLayerItem.tsx
  packages/webui/src/client/ui/Settings.tsx
  packages/webui/src/client/ui/Status.tsx
  packages/webui/src/client/ui/Status/MediaManager.tsx
  packages/webui/src/client/ui/SupportPopUp.tsx
  packages/webui/src/client/ui/TestTools/index.tsx
  packages/webui/src/client/ui/UserEditOperations/PropertiesPanel.tsx
  packages/webui/src/typings/velocity.d.ts
  packages/yarn.lock
Labels: 🐛🔨 bugfix
