Repository Sofie-Automation/sofie-core, pull requests merged in 2025-02, with the labels that each got.

#1343 feat: exclude pieces from part keepalive
  packages/blueprints-integration/src/documents/piece.ts
  packages/corelib/src/playout/__tests__/timings.test.ts
  packages/corelib/src/playout/timings.ts
  packages/job-worker/src/blueprints/context/lib.ts
  packages/job-worker/src/playout/timeline/__tests__/__snapshots__/rundown.test.ts.snap
  packages/job-worker/src/playout/timeline/__tests__/rundown.test.ts
  packages/job-worker/src/playout/timeline/generate.ts
  packages/job-worker/src/playout/timeline/part.ts
  packages/job-worker/src/playout/timeline/pieceGroup.ts
  packages/job-worker/src/playout/timeline/rundown.ts
  packages/webui/src/client/lib/__tests__/rundownTiming.test.ts
Labels: Contribution, Contribution from BBC

#1366 feat: add new SourceLayer Types
  meteor/server/api/rest/v1/typeConversion.ts
  meteor/server/lib/rest/v1/showstyles.ts
  packages/blueprints-integration/src/content.ts
  packages/shared-lib/src/core/model/ShowStyle.ts
  packages/webui/src/client/styles/_itemTypeColors.scss
  packages/webui/src/client/styles/rundownView.scss
  packages/webui/src/client/styles/shelf/adLibPanel.scss
  packages/webui/src/client/styles/shelf/dashboard.scss
  packages/webui/src/client/ui/ClockView/CameraScreen/index.tsx
  packages/webui/src/client/ui/PieceIcons/PieceCountdown.tsx
  packages/webui/src/client/ui/PieceIcons/PieceIcon.tsx
  packages/webui/src/client/ui/PieceIcons/Renderers/RemoteSpeakInputIcon.tsx
  packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartSecondaryPieces/StoryboardSecondaryPiece.tsx
  packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartThumbnail/Renderers/ThumbnailRendererFactory.tsx
  packages/webui/src/client/ui/SegmentStoryboard/StoryboardPartThumbnail/StoryboardPartThumbnail.scss
  packages/webui/src/client/ui/Settings/ShowStyle/SourceLayer.tsx
Labels: Contribution, Contribution from BBC

#1372 feat: add Shuttle WebHID prompter controller support
  packages/documentation/docs/user-guide/features/prompter.md
  packages/documentation/static/img/docs/main/features/contour-shuttle-webhid.jpg
  packages/webui/package.json
  packages/webui/src/client/styles/prompter.scss
  packages/webui/src/client/ui/Prompter/PrompterView.tsx
  packages/webui/src/client/ui/Prompter/controller/manager.ts
  packages/webui/src/client/ui/Prompter/controller/shuttle-webhid-device.ts
  packages/yarn.lock
Labels: Contribution, Contribution from TV 2 Norge

#1373 feat: add snapshot creation to Stable API
  meteor/server/api/rest/v1/__tests__/idempotencyService.spec.ts
  meteor/server/api/rest/v1/__tests__/rateLimitingService.spec.ts
  meteor/server/api/rest/v1/idempotencyService.ts
  meteor/server/api/rest/v1/index.ts
  meteor/server/api/rest/v1/middlewares.ts
  meteor/server/api/rest/v1/rateLimitingService.ts
  meteor/server/api/rest/v1/snapshots.ts
  meteor/server/api/rest/v1/typeConversion.ts
  meteor/server/api/rest/v1/types.ts
  meteor/server/api/snapshot.ts
  meteor/server/api/userActions.ts
  meteor/server/cronjobs.ts
  meteor/server/lib/rest/v1/index.ts
  meteor/server/lib/rest/v1/snapshots.ts
  meteor/server/migration/databaseMigration.ts
  packages/corelib/src/error.ts
  packages/corelib/src/snapshots.ts
  packages/corelib/src/worker/studio.ts
  packages/job-worker/src/playout/snapshot.ts
  packages/meteor-lib/src/api/shapshot.ts
  packages/openapi/api/actions.yaml
  packages/openapi/api/definitions/snapshots.yaml
  packages/openapi/src/__tests__/snapshots.spec.ts
Labels: Contribution, Contribution from TV 2 Norge

#1375 Feat: Consistent rundown activation logic
  packages/webui/src/client/lib/ModalDialog.tsx
  packages/webui/src/client/styles/modalDialog.scss
  packages/webui/src/client/ui/RundownView.tsx
Labels: Contribution, Contribution from BBC

#1364 Drag MOS Item on a Part to ingest
  packages/blueprints-integration/src/ingest.ts
  packages/blueprints-integration/src/userEditing.ts
  packages/corelib/src/dataModel/UserEditingDefinitions.ts
  packages/job-worker/src/blueprints/context/lib.ts
  packages/webui/src/client/styles/rundownView.scss
  packages/webui/src/client/ui/SegmentTimeline/Parts/SegmentTimelinePart.tsx
  packages/webui/src/client/ui/Shelf/ExternalFramePanel.tsx
  packages/webui/src/client/ui/UserEditOperations/RenderUserEditOperations.tsx
Labels: ✨ enhancement, Contribution, Contribution from BBC

#1377 fix: remove leftover publication names
  packages/meteor-lib/src/api/pubsub.ts
Labels: Contribution, Contribution from TV 2 Norge

#1362 chore: update dependencies
  .github/workflows/audit.yaml
  .github/workflows/node.yaml
  .github/workflows/prerelease-libs.yml
  .github/workflows/sonar.yaml
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/plugins/@yarnpkg/plugin-version.cjs
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  meteor/.yarnrc.yml
  meteor/package.json
  meteor/yarn.lock
  package.json
  packages/.prettierignore
  packages/blueprints-integration/package.json
  packages/corelib/package.json
  packages/documentation/package.json
  packages/job-worker/package.json
  packages/job-worker/src/__mocks__/collection.ts
  packages/job-worker/src/blueprints/cache.ts
  packages/job-worker/src/db/collection.ts
  packages/job-worker/src/db/collections.ts
  packages/job-worker/src/ingest/model/implementation/ExpectedPackagesStore.ts
  packages/lerna.json
  packages/live-status-gateway/package.json
  packages/meteor-lib/package.json
  packages/mos-gateway/package.json
  packages/openapi/package.json
  packages/package.json
  packages/playout-gateway/package.json
  packages/server-core-integration/package.json
  packages/server-core-integration/src/lib/CoreConnectionChild.ts
  packages/server-core-integration/src/lib/coreConnection.ts
  packages/server-core-integration/src/lib/ddpClient.ts
  packages/server-core-integration/src/lib/ddpConnector.ts
  packages/server-core-integration/src/lib/watchDog.ts
  packages/shared-lib/package.json
  packages/webui/package.json
  packages/webui/src/client/lib/triggers/codesToKeyLabels.ts
  packages/webui/src/client/lib/ui/containers/modals/Modal.tsx
  packages/webui/src/client/ui/SegmentTimeline/SegmentTimelineZoomControls.tsx
  packages/webui/src/client/ui/Shelf/HotkeyHelpPanel.tsx
  packages/yarn.lock
  yarn.lock
Labels: Contribution, Contribution from BBC

#1369 feat: customizable package status messages #1349
  meteor/server/api/blueprints/api.ts
  meteor/server/publications/pieceContentStatusUI/__tests__/checkPieceContentStatus.test.ts
  meteor/server/publications/pieceContentStatusUI/bucket/bucketContentCache.ts
  meteor/server/publications/pieceContentStatusUI/bucket/bucketContentObserver.ts
  meteor/server/publications/pieceContentStatusUI/bucket/publication.ts
  meteor/server/publications/pieceContentStatusUI/bucket/regenerateForItem.ts
  meteor/server/publications/pieceContentStatusUI/checkPieceContentStatus.ts
  meteor/server/publications/pieceContentStatusUI/messageFactory.ts
  meteor/server/publications/pieceContentStatusUI/rundown/publication.ts
  meteor/server/publications/pieceContentStatusUI/rundown/reactiveContentCache.ts
  meteor/server/publications/pieceContentStatusUI/rundown/regenerateItems.ts
  meteor/server/publications/pieceContentStatusUI/rundown/rundownContentObserver.ts
  packages/blueprints-integration/src/api/showStyle.ts
  packages/corelib/src/dataModel/Blueprint.ts
  packages/meteor-lib/src/collections/ExpectedPackages.ts
  packages/shared-lib/src/packageStatusMessages.ts
  packages/webui/src/client/lib/dev.ts
  packages/webui/src/client/ui/FloatingInspectors/VTFloatingInspector.tsx
  packages/webui/src/client/ui/RundownView/RundownNotifier.tsx
Labels: Contribution, Contribution from BBC

#1378 feat: allow adlib-actions to remove pieces from the current partInstance
  packages/blueprints-integration/src/context/onSetAsNextContext.ts
  packages/blueprints-integration/src/context/partsAndPieceActionContext.ts
  packages/job-worker/src/blueprints/__tests__/context-OnSetAsNextContext.test.ts
  packages/job-worker/src/blueprints/__tests__/context-OnTakeContext.test.ts
  packages/job-worker/src/blueprints/__tests__/context-adlibActions.test.ts
  packages/job-worker/src/blueprints/context/OnSetAsNextContext.ts
  packages/job-worker/src/blueprints/context/OnTakeContext.ts
  packages/job-worker/src/blueprints/context/adlibActions.ts
  packages/job-worker/src/blueprints/context/services/PartAndPieceInstanceActionService.ts
  packages/job-worker/src/blueprints/context/services/__tests__/PartAndPieceInstanceActionService.test.ts
Labels: Contribution, Contribution from BBC
