Repository Sofie-Automation/sofie-core, pull requests merged in 2025-07, with the labels that each got.

#1479 Fix: Underscore on all links after conversion to Bootstrap
  packages/webui/src/client/styles/main.scss
Labels: Contribution, Contribution from BBC

#1496 fix: Race condition in device change handling
  packages/playout-gateway/src/tsrHandler.ts
Labels: Contribution from EVS, Contribution

#1480 Persist infinites from AdLib testing mode into rundown
  meteor/server/api/rest/v1/typeConversion.ts
  meteor/server/lib/rest/v1/studios.ts
  packages/corelib/src/playout/__tests__/infinites.test.ts
  packages/corelib/src/playout/infinites.ts
  packages/job-worker/src/playout/infinites.ts
  packages/openapi/api/definitions/studios.yaml
  packages/shared-lib/src/core/model/StudioSettings.ts
  packages/webui/src/__mocks__/helpers/database.ts
  packages/webui/src/client/lib/RundownResolver.ts
  packages/webui/src/client/lib/__tests__/rundown.test.ts
  packages/webui/src/client/lib/rundown.ts
  packages/webui/src/client/ui/ClockView/DirectorScreen.tsx
  packages/webui/src/client/ui/ClockView/PresenterScreen.tsx
  packages/webui/src/client/ui/Prompter/PrompterView.tsx
  packages/webui/src/client/ui/Prompter/prompter.ts
  packages/webui/src/client/ui/SegmentContainer/withResolvedSegment.ts
  packages/webui/src/client/ui/Settings/Studio/Generic.tsx
  packages/webui/src/client/ui/Shelf/SegmentTimingPanel.tsx
  packages/webui/src/client/ui/Shelf/ShelfDashboardLayout.tsx
Labels: Contribution from EVS, Contribution

#1486 fix: findMarkerPosition always needs all parts available
  meteor/server/publications/lib/quickLoop.ts
  meteor/server/publications/partInstancesUI/publication.ts
  meteor/server/publications/partInstancesUI/reactiveContentCache.ts
  meteor/server/publications/partInstancesUI/rundownContentObserver.ts
Labels: Contribution, Contribution from BBC

#1489 fix: adjust padding of rundownlist
  packages/webui/src/client/ui/RundownList.tsx
Labels: Contribution, Contribution from BBC

#1478 fix: In-Out words was placed and styled wrong
  packages/webui/src/client/ui/PreviewPopUp/PreviewPopUp.scss
  packages/webui/src/client/ui/PreviewPopUp/PreviewPopUpContent.tsx
  packages/webui/src/client/ui/PreviewPopUp/PreviewPopUpContext.tsx
Labels: Contribution, Contribution from BBC

#1475 feat: Add flag to hide rundown header
  packages/documentation/docs/for-developers/url-query-parameters.md
  packages/webui/src/client/lib/notifications/NotificationCenterPanel.tsx
  packages/webui/src/client/lib/viewPort.ts
  packages/webui/src/client/styles/fromOrigo.scss
  packages/webui/src/client/styles/notifications.scss
  packages/webui/src/client/styles/statusbar.scss
  packages/webui/src/client/ui/RundownView.tsx
  packages/webui/src/client/ui/RundownView/RundownRightHandControls.tsx
  packages/webui/src/client/ui/SegmentList/SegmentList.scss
  packages/webui/src/client/ui/SegmentList/SegmentList.tsx
  packages/webui/src/client/ui/SegmentList/SegmentListContainer.tsx
  packages/webui/src/client/ui/SegmentList/SegmentListHeader.tsx
Labels: Contribution from EVS, Contribution

#1498 feat: add `manuallySelected` to OnSetAsNextContext
  packages/blueprints-integration/src/context/onSetAsNextContext.ts
  packages/job-worker/src/blueprints/__tests__/context-OnSetAsNextContext.test.ts
  packages/job-worker/src/blueprints/context/OnSetAsNextContext.ts
  packages/job-worker/src/playout/setNext.ts
Labels: Contribution, Contribution from TV 2 Norge

#1503 feat: support loading TSR devices as 'plugins'
  meteor/yarn.lock
  packages/documentation/docs/for-developers/device-integrations/tsr-plugins.md
  packages/playout-gateway/package.json
  packages/playout-gateway/src/configManifest.ts
  packages/playout-gateway/src/coreHandler.ts
  packages/playout-gateway/src/index.ts
  packages/playout-gateway/src/tsrDeviceRegistry.ts
  packages/playout-gateway/src/tsrHandler.ts
  packages/shared-lib/package.json
  packages/yarn.lock
Labels: Contribution from SuperFly.tv, Contribution
