Repository Sofie-Automation/sofie-core, pull requests merged in 2025-04, with the labels that each got.

#1409 fix: don't hide global adlibs from hidden sourceLayers
  packages/meteor-lib/src/uiTypes/Adlib.ts
  packages/webui/src/client/ui/Shelf/AdLibListView.tsx
  packages/webui/src/client/ui/Shelf/AdLibPanel.tsx
Labels: Contribution, Contribution from BBC

#1401 feat: improve ab notifications and logging
  packages/corelib/src/dataModel/RundownPlaylist.ts
  packages/job-worker/src/playout/abPlayback/__tests__/abPlayback.spec.ts
  packages/job-worker/src/playout/abPlayback/__tests__/abPlaybackResolver.spec.ts
  packages/job-worker/src/playout/abPlayback/__tests__/applyAssignments.spec.ts
  packages/job-worker/src/playout/abPlayback/abPlaybackResolver.ts
  packages/job-worker/src/playout/abPlayback/abPlaybackSessions.ts
  packages/job-worker/src/playout/abPlayback/applyAssignments.ts
  packages/job-worker/src/playout/abPlayback/index.ts
Labels: Contribution, Contribution from BBC

#1426 Documentation clarification on Screens and Views
  packages/documentation/docs/user-guide/concepts-and-architecture.md
  packages/documentation/docs/user-guide/features/prompter.md
  packages/documentation/docs/user-guide/features/sofie-views-and-screens.mdx
Labels: Contribution from SuperFly.tv, Contribution

#1423 feat: replace deprecated mongodb fields with projection
  meteor/server/api/blueprintConfigPresets.ts
  meteor/server/api/blueprints/api.ts
  meteor/server/api/buckets.ts
  meteor/server/api/cleanup.ts
  meteor/server/api/deviceTriggers/StudioObserver.ts
  meteor/server/api/evaluations.ts
  meteor/server/api/ingest/rundownInput.ts
  meteor/server/api/integration/expectedPackages.ts
  meteor/server/api/integration/media-scanner.ts
  meteor/server/api/integration/mediaWorkFlows.ts
  meteor/server/api/mediaManager.ts
  meteor/server/api/peripheralDevice.ts
  meteor/server/api/playout/playout.ts
  meteor/server/api/rundown.ts
  meteor/server/api/studio/api.ts
  meteor/server/api/studio/lib.ts
  meteor/server/collections/collection.ts
  meteor/server/collections/lib.ts
  meteor/server/coreSystem/checkDatabaseVersions.ts
  meteor/server/coreSystem/index.ts
  meteor/server/migration/upgrades/showStyleBase.ts
  meteor/server/migration/upgrades/studio.ts
  meteor/server/optimizations.ts
  meteor/server/publications/buckets.ts
  meteor/server/publications/organization.ts
  meteor/server/publications/packageManager/expectedPackages/contentObserver.ts
  meteor/server/publications/packageManager/expectedPackages/publication.ts
  meteor/server/publications/packageManager/packageContainers.ts
  meteor/server/publications/packageManager/playoutContext.ts
  meteor/server/publications/partInstancesUI/rundownContentObserver.ts
  meteor/server/publications/partsUI/rundownContentObserver.ts
  meteor/server/publications/peripheralDevice.ts
  meteor/server/publications/peripheralDeviceForDevice.ts
  meteor/server/publications/rundown.ts
  meteor/server/publications/segmentPartNotesUI/rundownContentObserver.ts
  meteor/server/publications/showStyleUI.ts
  meteor/server/publications/studio.ts
  meteor/server/publications/studioUI.ts
  meteor/server/publications/system.ts
  meteor/server/publications/timeline.ts
  meteor/server/publications/translationsBundles.ts
  meteor/server/serverOptimisations.ts
  meteor/server/systemStatus/blueprintVersions.ts
Labels: Contribution

#1421 chore: add documentation page for `processIngestData`
  packages/documentation/docs/for-developers/for-blueprint-developers/manipulating-ingest-data.md
Labels: Contribution, Contribution from BBC

#1416 fix: duration of pieces with 'now' start time
  packages/job-worker/src/playout/timeline/multi-gateway.ts
Labels: Contribution, Contribution from TV 2 Norge

#1405 feat: support hosting sofie under subdirectory
  meteor/__mocks__/_setupMocks.ts
  meteor/package.json
  meteor/server/api/peripheralDevice.ts
  meteor/server/api/rest/api.ts
  meteor/server/api/rest/koa.ts
  meteor/server/lib.ts
  meteor/server/webmanifest.ts
  meteor/tsconfig-base.json
  meteor/yarn.lock
  packages/webui/src/client/lib/ui/icons/notifications.tsx
  packages/webui/src/client/styles/_header.scss
  packages/webui/src/client/ui/App.tsx
  packages/webui/src/client/ui/PreviewPopUp/PreviewPopUpContext.tsx
  packages/webui/src/client/ui/PreviewPopUp/Previews/IFramePreview.tsx
  packages/webui/src/client/ui/SegmentTimeline/Renderers/TransitionSourceRenderer.tsx
  packages/webui/src/client/ui/Settings/BlueprintSettings.tsx
  packages/webui/src/client/ui/Settings/RundownLayoutEditor.tsx
  packages/webui/src/client/ui/Settings/SnapshotsView.tsx
  packages/webui/src/client/ui/Settings/SystemManagement.tsx
  packages/webui/src/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx
  packages/webui/src/client/ui/Settings/components/triggeredActions/TriggeredActionsEditor.tsx
  packages/webui/src/client/ui/StudioScreenSaver/StudioScreenSaver.tsx
  packages/webui/src/client/ui/i18n.ts
  packages/webui/src/client/url.ts
  packages/webui/src/main.tsx
  packages/webui/vite.config.mts
  scripts/run.mjs
Labels: Contribution, Contribution from BBC

#1419 feat: Director's Screen
  meteor/i18n/nb.po
  meteor/i18n/nn.po
  meteor/i18n/template.pot
  packages/blueprints-integration/src/documents/pieceGeneric.ts
  packages/documentation/docs/user-guide/features/sofie-views-and-screens.mdx
  packages/documentation/static/img/docs/main/features/director-screen-example.png
  packages/webui/src/client/lib/Components/CounterComponents.tsx
  packages/webui/src/client/styles/_colorScheme.scss
  packages/webui/src/client/styles/countdown/director.scss
  packages/webui/src/client/styles/counterComponents.scss
  packages/webui/src/client/styles/defaultColors.scss
  packages/webui/src/client/styles/fonts/roboto.scss
  packages/webui/src/client/styles/fonts/sass/_RobotoFlex.scss
  packages/webui/src/client/styles/fonts/sass/_mixins.scss
  packages/webui/src/client/styles/fonts/sass/roboto.scss
  packages/webui/src/client/styles/main.scss
  packages/webui/src/client/ui/ClockView/ClockView.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewFreezeCount.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewPieceIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewPieceIcons.scss
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewPieceName.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/CamInputIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/GraphicsInputIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/LiveSpeakInputIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/LocalInputIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/RemoteInputIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/RemoteSpeakInputIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/SplitInputIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/UnknownInputIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/ClockViewRenderers/VTInputIcon.tsx
  packages/webui/src/client/ui/ClockView/ClockViewPieceIcons/utils.ts
  packages/webui/src/client/ui/ClockView/DirectorScreen.tsx
  packages/webui/src/client/ui/PieceIcons/PieceIcons.scss
  packages/webui/src/client/ui/PieceIcons/Renderers/RemoteInputIcon.tsx
  packages/webui/src/client/ui/PieceIcons/Renderers/RemoteSpeakInputIcon.tsx
  packages/webui/src/client/ui/util/AdjustLabelFit.tsx
  packages/webui/src/fonts/roboto-gh-pages/fonts/Regular/RobotoFlex-Regular.ttf
Labels: Contribution, Contribution from BBC
